### ISSUE TITLE
Thought on approach

### ISSUE THREAD

**Issue by cometkim** [Js-Brecht/gatsby-plugin-ts-config#1]
Hey @ Js-Brecht, thank you for the nice work and I think this should have happened earlier.

I looked at this in the morning and thought a few things.

1. Isolating the `.gatsby` folder look pretty, but 3rd party plugins that hardcode the `gatsby- *` file path can cause problems. Ironically, even this plugin one of them itself.

2. Using a custom compiler with gatsby code can break compatibility with Gatsby's query compiler. Only transpilers can be used, and `babel-preset-gatsby` and `babel-preset-gatsby-package` are the only "official" support for it.

3. I prefer to use babel-node over ts-node because of 2 and the extendabilities (ex, I use `babel/plugin-transform-named-capturing-groups-regex` for my plugin). If you don't consider extensions, alternatives like sucrase might be a better option. because it shouldn't be "compile" and just faster is better.

4. Is it support yarn 2? Gatsby puts a lot of effort into compatibility with yarn 2, and this kind of meta plugin should do as well.

**Comment by Js-Brecht** [comment]
> 1. Isolating the `.gatsby` folder look pretty, but 3rd party plugins that hardcode the `gatsby- *` file path can cause problems.

Yeah, it works for what I'm doing, but I understand how it can still be necessary to keep the files in the root.  There were a few things that were particularly opinionated that I forgot to fix before I published, but it should work now with configurations in the root.

> Ironically, even this plugin one of them itself.

I've run into a couple of snags, and I think I've worked them out for the most part.  If you still notice problems, care to share?  One thing I'm really not too sure about is how it is going to interact with 3rd party plugins, and that's one place I can't test thoroughly.

> 2. Using a custom compiler with gatsby code can break compatibility with Gatsby's query compiler. Only transpilers can be used, and `babel-preset-gatsby` and `babel-preset-gatsby-package` are the only "official" support for it.

🤔 Does Gatsby read directly off the disk when it picks up `gatsby-node` to look for queries, or does it use `require()`?  I'd have to check to see, and using Gatsby's `graphql` queries in `gatsby-node` is something that I do need to test.  If it's pretty much the same as `src` query processing, chances are pretty high that it won't even **_see_** the queries when this plugin is being used, especially if it only looks for `.js` scripts.

I need to go examine the query processing for `gatsby-node`.  Thanks for bringing it to my attention.

> 3. I prefer to use babel-node over ts-node because of 2 and the extendabilities (ex, I use `babel/plugin-transform-named-capturing-groups-regex` for my plugin).

I have a feeling that using babel will be the general approach when implementing this type of feature into the Gatsby core.  I just have never been a fan of using babel for processing Typescript, mainly because it winds up giving me a headache.  I do agree, though, performance is important; and babel alone would be faster than ts-node; but is babel-node faster, and does it do type checking?  I haven't used it.

> If you don't consider extensions, alternatives like sucrase might be a better option. because it shouldn't be "compile" and just faster is better.

I will have to check it out and see what it's like.

I'm open to trying anything that ensures compatibility with Gatsby, is fast, and can be super simple to use for consumers.

> 4. Is it support yarn 2? Gatsby puts a lot of effort into compatibility with yarn 2, and this kind of meta plugin should do as well.

Also something I need to test.  It really depends on how `berry` hooks into `require()`, or if they do at all.  It's been a while since I've looked at their work, and I never really looked to see how they hook into node's module resolution.  `ts-node` uses `require.extensions`, so if `berry` does too, then they will probably conflict.  `require.extensions` **_is_** deprecated, though, so it would be very interesting to see how `berry` handles it.

**Comment by Js-Brecht** [comment]
After some preliminary tests, this plugin, as it is, doesn't appear to cause issues with _**resolving**_ queries in `gatsby-node`, but there's more than likely use cases/purposes I haven't explored.  If you could point me in a direction, I'd really appreciate it, too.

I will keep testing with various scenarios.  Also, in the meantime, I'll see how well I can make it work with `babel` or `sucrase`.

**Comment by cometkim** [comment]
> I do agree, though, performance is important; and babel alone would be faster than ts-node; but is babel-node faster, and does it do type checking? I haven't used it.

Type checking can still be done explicitly with `tsc`, and sometimes it is much more useful to separate it from build in the workflow.

It's all about adding `preset-typescript` to transpiling typescripts with babel, essentially the same as `tsc --transpile-only`.

**Comment by Js-Brecht** [comment]
So I decided not to use `sucrase`.  Being able to define custom extensions/plugins, even at this stage, is too important.

I've got a POC with babel mostly done; there's just some work I need to do for module resolution (should be able to use `babel-plugin-module-resolver`, I think).  I just wanted to get your thoughts on a couple things, since documentation on most of Babel's process outside of its CLI seems to be kind of scarce, or insufficient.

* First thing, do you have good sources of documentation?  I'm finding myself having to dig through their code so I can see how things work, just to figure out how to use them, because I just don't get the information I need from their docs.  Would be much nicer if there were more thorough descriptions of the way things operate and how to use them properly.  It would save time.

* Since reading & processing `gatsby-config` and `gatsby-node` happen in a different layer than the site bundling, I'm having to do ahead-of-time compiling, just so the configs can be compiled by gatsby.  This means I have to look for any imports/requires those two Gatsby endpoints are performing, and follow that tree on down, transpiling as I go; otherwise, the whole thing breaks.  Do you know of a plugin/configuration/babel module that will do this, because if there isn't one, I will probably need to write my own so that I can streamline the process.  Currently, traversing the AST is separate from the transformation process, so it takes extra steps that I think could be performed during the first pass.

* This ahead-of-time transpiling really feels a lot like I'm recreating a bundler.  Not to mention, it also means a minimum of twice the filesystem interaction than on-the-fly transpiling & compiling.  In the tests I've done, it actually feels slower than using something like `ts-node`, but I haven't done any true benchmarks.  What are your thoughts on using something like `@babel/register`?  If there is query processing that needs to be, or can be, done during transpilation/compilation, I'm pretty sure I can hook into the process to make it happen on the fly.

**Comment by Js-Brecht** [comment]
Oh, and one more:

* I wonder if it makes sense to try to keep the userland babel config separate from this plugin.  The user's babel config would mostly pertain to `src` code that is being bundled through Webpack, while this is actually targeting Node/CommonJS, so the transformation is different and will need less.  I was thinking about a plugin option that lets the user define babel presets/plugins that this process should use, instead of using the user's `.babelrc`.  Or, additionally, including an option that allows babel to read their `.babelrc`; that way, if they know that what they're defining in their `.babelrc` they want to run through both Node and Webpack, then they don't have to define it in multiple places.

**Comment by cometkim** [comment]
> So I decided not to use sucrase. Being able to define custom extensions/plugins, even at this stage, is too important.

I think letting the user specify the actual runtime would be better. Many users are already doing so in scripts in their `package.json`. (I'm actually using sucrase for some gatsby projects)

> First thing, do you have good sources of documentation? I'm finding myself having to dig through their code so I can see how things work, just to figure out how to use their modules, because I just don't get the information I need from their docs. Would be much nicer if there were more thorough descriptions of the way things operate and how to use them properly. It would save time.

What [this plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-module-resolver/) has already done will help. (README is just all.)  Actually, it's much more intuitive than TypeScript's baseUrl + paths.

> Since reading & processing gatsby-config and gatsby-node happen in a different layer than the site bundling, I'm having to do ahead-of-time compiling, just so the configs can be compiled by gatsby. This means I have to look for any imports/requires those two Gatsby endpoints are performing, and follow that tree on down, transpiling as I go; otherwise, the whole thing breaks. Do you know of a plugin/configuration/babel module that will do this, because if there isn't one, I will probably need to write my own so that I can streamline the process. Currently, traversing the AST is separate from the transformation process, so it takes extra steps that I think could be performed during the first pass.

`babel-preset-gatsby` for site bundling and `babel-preset-gatsby-package` is for `gatsby-node` and `gatsby-config`. That's all. And if a user has its own custom config(.babelrc, babel.config.js, etc), then the user will take the control. (see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/babel-loader.js)

> This ahead-of-time transpiling really feels a lot like I'm recreating a bundler. Not to mention, it also means a minimum of twice the filesystem interaction than on-the-fly transpiling & compiling. In the tests I've done, it actually feels slower than using something like ts-node, but I haven't done any true benchmarks. What are your thoughts on using something like @babel/register? If there is query processing that needs to be, or can be, done during transpilation/compilation, I'm pretty sure I can hook into the process to make it happen on the fly.

Using register scripts like `@babel/register` or `tsconfig-paths` is an option. However, the details should be chosen by the user. As already discussed, it's better and feeling consistent to define a separate lifecycle such as gatsby-ts so that users can hook it.

> I was thinking about a plugin option that lets the user define babel presets/plugins that this process should use, instead of using the user's .babelrc. Or, additionally, including an option that allows babel to read their .babelrc; that way, if they know that what they're defining in their .babelrc they want to run through both Node and Webpack, then they don't have to define it in multiple places.

This can be difficult because Gatsby already allows user's custom babelrc. If you want it, it should be provided via Gatsby core.

**Comment by cometkim** [comment]
I don't wanna say that you can't do this. In fact, you have a pretty neat project configuration that actually works.

I certainly didn't think about this as much as you do, But I think It's a good attempt to present possibilities to Gatsby users.

Closing this, so you do spend more productive time.
Feel free to call me if you need further discussion or feedback.

**Comment by Js-Brecht** [comment]
Thanks for the feedback @cometkim
