### ISSUE TITLE
'loose' mode configuration must be the same for both @babel/plugin-proposal-class-properties and @babel/plugin-proposal-private-methods

### ISSUE THREAD

**Issue by Mrtenz** [Js-Brecht/gatsby-plugin-ts-config#11]
Using this plugin with Babel as transpiler results in the following error:

```
  Error: [gatsby-plugin-ts-config] An error occurred while reading your gatsby-config!
  /.gatsby/gatsby-config.ts: 'loose' mode configuration must be the same for both @babel/plugin-proposal-class-properties and @babel/plugin-proposal-private-methods
```

I'm not using a custom Babel config, so I'm assuming this is an issue with this plugin. Setting `babel` to `false` and `tsNode` to `true` resolves it, but I'd like to use Babel if possible.

**Comment by Js-Brecht** [comment]
Are you able to share your project @Mrtenz?

**Comment by Mrtenz** [comment]
Here's a minimal repo where I'm able to reproduce:
https://github.com/Mrtenz/gatsby-plugin-ts-config-test

Simply running `gatsby build` or `gatsby develop` will trigger the error.

**Comment by Js-Brecht** [comment]
I use the same preset that Gatsby uses to transpile their own files, with an absolute runtime path injected for `@babel/plugin-transform-runtime` for yarn2 compatibility.  The only reason I can think of that it may be throwing that error is because [`@babel/preset-env` has `loose: true`](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby-package/index.js#L30), but [`@babel/plugin-proposal-class-properties` doesn't](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby-package/index.js#L42).  

AFAIK, `@babel/preset-env` will already load up `@babel/plugin-proposal-class-properties` **AND** `@babel/plugin-proposal-private-methods`, with a uniform set of options.  My guess is that the inclusion of `@babel/plugin-proposal-class-properties` in the preset overrides what `@babel/preset-env` is doing, so it throws that error.

What I don't understand is why it is throwing now, because it's been like that for a while, and running successfully.  Maybe babel changed the way they process those options at some point recently.

I will take a look and see what I can come up with.

**Comment by Mrtenz** [comment]
This may be related: babel/babel#11622

**Comment by Js-Brecht** [comment]
That's exactly why.  As soon as I add that option to `@babel/plugin-proposal-class-properties` in `babel-preset-gatsby-package`, the error goes away.  I will submit a PR to Gatsby to fix the error... still pretty strange that it started breaking all of a sudden.

**Comment by Js-Brecht** [comment]
[This](https://github.com/babel/babel/blob/e6d873e061a967c64c9999f15b831aa121cc5a68/packages/babel-preset-env/src/index.js#L303-L326) is what's new; [merged in](https://github.com/babel/babel/commit/e6d873e061a967c64c9999f15b831aa121cc5a68#) 13 hours ago.  Pretty sure that's what caused it to start breaking.. they added some options constraints between a few plugins.

The semver for `@babel/preset-env` in  `babel-preset-gatsby-package` is causing the latest version to be pulled, so that's why that's happening.  You could add a resolution for `@babel/preset-env` to an earlier version as a workaround for now.

**Comment by Js-Brecht** [comment]
https://github.com/gatsbyjs/gatsby/pull/24640

**Comment by Js-Brecht** [comment]
Thanks for bringing that to my attention, by the way :pray:

**Comment by balibebas** [comment]
Adding a [selective dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) for `@babel/preset-env` and pinning the dependency to a babel fix piror to the one introducing the code change described and linked [9 days ago](https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/11#issuecomment-636312611) does not address the issue. So it's unlikely the babel code change described is what's causing the issue.

**Comment by Js-Brecht** [comment]
This works for me:
```json
  "resolutions": {
    "@babel/preset-env": "7.10.1",
    "@babel/helper-create-class-features-plugin": "7.9.6",
    "@babel/plugin-proposal-class-properties": "7.10.1"
  }
```

**Comment by Js-Brecht** [comment]
Can you guys please try `gatsby-plugin-ts-config@0.2.3-pre.1`?

**Comment by Mrtenz** [comment]
`gatsby-plugin-ts-config@0.2.3-pre.1` works for me with `babel: true` :+1:

**Comment by Js-Brecht** [comment]
v0.2.3 is published :rocket:
