### ISSUE TITLE
Handling custom plugins.

### ISSUE THREAD

**Issue by rroslaniec** [Js-Brecht/gatsby-plugin-ts-config#12]
Hey,
I've figure it out that after using that plugin mine custom plugins are not discovered - even I've added also gatsby-config.js files to them.

```
 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-fonts" plugin declared in "/path/to/project/node_modules/gatsby-plugin-ts-config/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /path/to/project/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/dist/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby-plugin-fonts
 - /path/to/node_modules/gatsby-plugin-fonts
 - /Users/rroslaniec/node_modules/gatsby-plugin-fonts
 - /Users/node_modules/gatsby-plugin-fonts
 - /node_modules/gatsby-plugin-fonts
```
There is no lookup in /path/to/project/plugins folders (https://www.gatsbyjs.org/docs/creating-a-local-plugin/)

gatsby-plugin-fonts is our custom local plugin.

**Comment by Js-Brecht** [comment]
Yeah, that's one drawback I hadn't thought of yet.  Thanks for bringing it up.

This plugin takes advantage of the "theme" system that Gatsby uses, which allows plugins to have a `gatsby-config`.  This lets it set up the transpiler for `gatsby-config` and `gatsby-node`, which is what it needs so that you can write them in typescript.  The problem with that is your config basically gets relegated to the next level.

So instead of doing this to get all of your default site plugins:
`default-site -> gatsby-config`

It is now doing this:
`default-site -> gatsby-plugin-ts-config -> gatsby-config`

And Gatsby doesn't look in the `plugins` folder local to any of the plugins, because that just opens up a can of worms.

There's a couple of things that can be done.  If you make the path to the local plugin an absolute path, then it should work without a problem:
```js
// If gatsby-config.ts is in a subdirectory
const localPlugins = path.join.bind(path, path.resolve(__dirname, '..', 'plugins'));
const resolveLocalPlugin = (project) => path.dirname(
  require.resolve(
    localPlugins(project, 'package.json')
  )
)
module.exports = {
  plugins: [
    resolveLocalPlugin('gatsby-plugin-fonts')
  ]
}
```

OR, I could include a utility that will do this for you... which I think I will do anyway.  This plugin is due for some more work, to make static typing for `gatsby-config` better.

**Comment by rroslaniec** [comment]
@Js-Brecht I tried that solution but one more thing - custom plugins are also written in TypeScript :)
I tried adding tsconfig, gatsby-config but nothing helps there.

Error:

```
  Error: /path/to/project/plugins/gatsby-plugin-fonts/gatsby-node.ts:1
  (function (exports, require, module, __filename, __dirname) { import { CreateWebpackConfigArgs } from "gatsby";
                                                                       ^
  SyntaxError: Unexpected token {
```

**Comment by Js-Brecht** [comment]
So I'm thinking that the API may look like this:
```ts
// gatsby-config.ts

import { resolvePlugin } from 'gatsby-plugin-ts-config';

export default ({ projectRoot }) => {
  plugins: [
    resolvePlugin('foo-plugin'),
    {
      resolve: resolvePlugin('bar-plugin'),
      options: {
        someOptions: 'thisValue',
      }
    }
  ]
}
```

This could resolve plugins from
* local plugins directory
* node_modules

Probably in that order.  Not only will it resolve the path for Gatsby, but it will collect the paths of the various `gatsby-*` files and store them on [OptionsHandler](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/src/utils/options-handler.ts#L13).

After the default site's `gatsby-config.ts` file has finished compiling, it will have collected the paths of all of the additional requested plugins, too.  It can then run through that list, compiling as it goes.

One downside to it being done this way is that those files will not be available to the `gatsby-config` function, which means they cannot be passed to other plugins.  For example, when `gatsby-plugin-typegen` supports passing additional files to it in order to generate types from queries in them, it won't be able to watch those additional plugin files, because the `gatsby-config` function won't know about them until after it's done resolving.

I think one way to overcome this downside is to execute the `resolvePlugin()` function before the exported function, instead of inside of it:

```ts
// gatsby-config.ts

import { resolvePlugin } from 'gatsby-plugin-ts-config';

const fooPlugin = resolvePlugin('foo-plugin');
const barPlugin = resolvePlugin('bar-plugin');

export default ({ projectRoot, endpoints }) => {
  plugins: [
    fooPlugin,
    {
      resolve: barPlugin,
      options: {
        someOptions: 'thisValue',
      }
    },
    {
      resolve: 'gatsby-plugin-typegen',
      options: {
        watchFiles: endpoints.node,
      }
    }
  ]
}
```

I suppose an alternative syntax to `resolvePlugin()` is to make it mimic the structure of the `plugins[]` array.

```ts
const resolvedPlugins = resolvePlugins([
  'foo-plugin',
  {
    resolve: 'bar-plugin',
    options: {
      someOption: 'thisValue',
    }
  }
]);

export default ({ projectRoot, endpoints }) => {
  plugins: [
    ...resolvedPlugins,
    {
      resolve: 'gatsby-plugin-typegen',
      options: {
        watchFiles: endpoints.node,
      }
    }
  ]
}
```

----

@rroslaniec let me know if you have any thoughts/suggestions.

**Comment by rroslaniec** [comment]
@Js-Brecht nice - well prepared draft!

I think the last idea is the easiest to migrate. Once plugins written in typescript already exist, you can use copy-paste and throw them into this function. And in addition I am in favor of writing fewer characters :)
However, it doesn't matter for new users.

While I was browsing the gatsby documentation, I came across to https://www.gatsbyjs.org/docs/creating-a-local-plugin/#using-requireresolve-and-a-filepath - you probably would have to consider that too.

**Comment by Js-Brecht** [comment]
> While I was browsing the gatsby documentation, I came across to https://www.gatsbyjs.org/docs/creating-a-local-plugin/#using-requireresolve-and-a-filepath - you probably would have to consider that too.

Yes, this feature would probably be using `require.resolve` behind the scenes, at least to find the directory for the plugin.  It's a pretty easy method for resolving the absolute path to packages, without having to do additional FS checks/realpath resolutions; it will basically packages all of that up into one function call.

However, this plugin already has its own method for resolving `gatsby-*` endpoints, once the parent directory is found.  There's not a pre-packaged method provided for handling that the way it needs to be done.

The purpose for this API will be twofold: 
1. Return a plugin array in a format that Gatsby can understand, with the paths already resolved
2. Grab the list of `gatsby-*` endpoints from those plugins and transpile them, so that Gatsby can read them later.

This actually works out really well, because I was already planning on writing a function for resolving Typescript plugins which will allow the use of a proper discriminated union, so that the options you include for the plugins will be strongly typed.  The way this project was originally written doesn't work how I wanted it to with discriminated unions; because it needs to allow untyped options, too, there winds up being nothing to discriminate, so it doesn't work how it needs to 😆.

This will give me an opportunity to produce something that will allow for type checking & intellisense on any plugin's options properties.

I'm going to try to get it done this weekend.  I've just been really busy lately.  Hard to find time to work on these personal projects.

**Comment by Js-Brecht** [comment]
@rroslaniec Okay, I've made a great deal of progress on this feature.  I just need to do some testing. I have published a release candidate as `gatsby-plugin-ts-config@next`, because I'd like to open it up for testing, and it might be another week before I can finish.  I don't have time to do it all tonight.

----

Before I continue, I would like to define a couple of terms:

* `ITSConfigFn`: The type utility that defines the function that can be exported from `gatsby-config` and `gatsby-node`.  It receives the following options:
  * `projectRoot`
  * `configDir`
  * `cacheDir`
  * `endpoints`
* `endpoints` contains an object that looks like this:
  ```ts
  {
    node: string[];
    config: string[];
    plugin: {
      [pluginName: string]: {
        node: string[];
        config: string[];
      }
    }
  }
  ```
  * The first index of each `string[]` is the first file... the root `gatsby-config` or the root `gatsby-node` for the default site, or the root `gastby-config`/`gatsby-node` for each plugin listed.  All of the indexes following that is the import chain; all of the modules that are imported by the first, and every successive module.

----

This is a major version release, because there have been some breaking changes in the public API.  Mostly the only thing that was removed was second parameter in `ITSConfigFn` for the discriminated types for defining plugin options.  Because the plugin array needs to accept untyped plugins, that parameter wasn't able to act as an actual discriminated union.

There is now a new export, `includePlugins`.  It can be passed type interfaces for different plugin options as the first generic parameter.  It works just like it worked for `ITSConfigFn`, except now, if you do define them, you won't be able to include plugins without types.  You can, however, call `includePlugins` multiple times if you want to also include untyped plugins.

`includePlugins` has a couple of overloads.
* You can define an array of plugins, just like you can for the normal config export, as well as a callback function in the second parameter that takes the same parameters as `ITSConfigFn`.
* You can pass only the array,
* Or, you can pass just the callback function.

The overload looks like this:
```ts
    <T extends IGatsbyPluginDef = IGatsbyPluginDef>(pluginsCb: IPluginDetailsCallback<T>): void;
    <T extends IGatsbyPluginDef = IGatsbyPluginDef>(plugins: T[], pluginsCb?: IPluginDetailsCallback<T>): void;
```

The order of processing is as follows:
1. The array of plugins for each `includePlugins` will be resolved in order, and then compiled
    * This means that the resolved endpoints and imports will be passed to the main `ITSConfigFn`.
2. The main `ITSConfigFn` will have all of its plugins resolved
    * The plugins will now have all of their paths resolved before being passed to Gatsby.  This fixes an issue with yarn 2.
        * I recently fixed an issue in the themes plugin processing that Gatsby does, so that a theme's plugins could be resolved properly when using yarn 2 or pnpm.  That fix breaks this plugin because this plugin would no longer be operating within the scope of the default site, meaning it wouldn't be able to resolve any of your default site plugins.  That is a critical failure, with a 100% stop rate.  Resolving all of the plugin's before they get back to Gatsby is a pretty solid resolution.
3. All of the callbacks that were defined in the `includePlugins` calls will be resolved in the order they were defined.
    * Each time a callback is called, it will receive a fresh/up-to-date list of `endpoints`.  This means that each successive callback will receive all of the resolved plugins, and those plugin's imports, that the last callback generated.

It is important to note that the order of processing is also the order that the plugins will appear in the final result that is fed back to Gatsby.  If you have plugins that rely on a specific order, then that must be accounted for.

----

I am including an example usage below that I used for some preliminary tests.  Branch is [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/tree/plugin-resolver).  Please let me know as soon as/if you encounter any issues.  I will try to wrap this up within the next few days, but it may need to wait until next weekend.

<details>
<summary>Example usage</summary>

```ts
import { IPluginOptions as IPnpmPluginOptions } from 'gatsby-plugin-pnpm';
import { ITSConfigFn, includePlugins, IGatsbyPluginDef } from 'gatsby-plugin-ts-config';
import { PluginOptions as ITypegenPluginOptions } from 'gatsby-plugin-typegen/types';
import { FileSystemConfig } from 'gatsby-source-filesystem';

includePlugins<
    | IGatsbyPluginDef<'gatsby-plugin-pnpm', IPnpmPluginOptions>
    | IGatsbyPluginDef<'gatsby-plugin-typegen', ITypegenPluginOptions>
    | FileSystemConfig
>([
    'gatsby-plugin-pnpm',
], ({ projectRoot }) => ([
    {
        resolve: 'gatsby-plugin-typegen',
        options: {
            outputPath: `${projectRoot}/.gatsby/graphql/types.ts`,
            emitSchema: {
                [`${projectRoot}/.gatsby/graphql/introspection.json`]: true,
                [`${projectRoot}/.gatsby/graphql/schema.graphql`]: true,
            },
            emitPluginDocuments: {
                [`${projectRoot}/.gatsby/graphql/plugin-documents.graphql`]: true,
            },
        }
    },
    {
        resolve: `gatsby-source-filesystem`,
        options: {
            name: `images`,
            path: `${projectRoot}/src/images`,
        },
    },
]))

const gatsbyConfig: ITSConfigFn<'config'> = ({
    projectRoot,
}) => ({
    siteMetadata: {
        title: `Gatsby PNPM/Typescript Starter`,
        description: `Kick off your next, great Gatsby project with this starter. This starter ships with the main Gatsby configuration files you might need, including support for PNPM and Typescript.  It also includes a file structure that is conducive for developing your Gatsby configuration files with Typescript`,
        author: `@js-brecht`,
    },
    plugins: [
        {
            resolve: `gatsby-plugin-ts`,
            options: {
                codegen: false,
            }
        },
        `gatsby-plugin-tsconfig-paths`,
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${projectRoot}/src/images`,
            },
        },
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `gatsby-starter-default`,
                short_name: `starter`,
                start_url: `/`,
                background_color: `#663399`,
                theme_color: `#663399`,
                display: `minimal-ui`,
                icon: `${projectRoot}/src/images/gatsby-icon.png`, // This path is relative to the root of the site.
            },
        },
        // this (optional) plugin enables Progressive Web App + Offline functionality
        // To learn more, visit: https://gatsby.dev/offline
        // `gatsby-plugin-offline`,
    ]
});

export default gatsbyConfig;
```

</details>

**Comment by Js-Brecht** [comment]
@rroslaniec Sorry it's taken me this long to get this finished.  Sneaking in the few hours I needed to implement this has been tough.

The new feature is about ready for production; just needs to have a little bit more testing done out in the wild.  It is published right now as `gatsby-plugin-ts-config@next`, which is release candidate 3.  I've worked out any issues I could find; I think all that may be left is whatever issues exist under circumstances that I haven't been able to foresee.

There are some changes to the `endpoints` passed to the `gatsby-config` function.  You can read about it [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/plugin-resolver/README.md#gatsby--as-a-function-parameters).

The new API is detailed [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/plugin-resolver/README.md#gatsby-config-utilites), as well as the new type utility [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/plugin-resolver/README.md#type-utilities).  I have also updated the example to show the usage of the new function [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/plugin-resolver/README.md#examples).

Take it for a spin, if you would, and please drop a line about it on #14.  If you have any suggestions or encounter any issues, please let me know.

Thanks!

**Comment by rroslaniec** [comment]
Hey @Js-Brecht sorry for delay. Right now I got some time to test your solution. ALMOST works - right now normal plugins are not discoverable.

  **Error: [gatsby-plugin-ts-config] Unable to locate plugin gatsby-plugin-typescript**


gatsby-config.ts looks like this:

```ts
includePlugins([
 //local plugins
]);

const gatsbyConfig = {
  //some config
  plugins: [
    "gatsby-plugin-typescript",
    //and other
  ],
};

export default gatsbyConfig;

```

That do not depends on `gatsby-plugin-typescript` - whatever plugin you put at the first place will throw.

**Comment by Js-Brecht** [comment]
Let's move this discussion to the PR, if you don't mind
