### ISSUE TITLE
Unable to type already defined GraphQL types

### ISSUE THREAD

**Issue by chriscarrillo** [Js-Brecht/gatsby-plugin-ts-config#18]
First of all, I love the plugin, and thank you so much for building it! 😄 

I am using Kentico as the CMS for my application. The [@kentico/gatsby-source-kontent](https://github.com/Kentico/kontent-gatsby-packages/tree/master/packages/gatsby-source-kontent) package defines the GraphQL types. I try to leverage the [sourceNodes API](https://www.gatsbyjs.com/docs/node-apis/#sourceNodes) to create special typing:
```
export const sourceNodes = ({actions: {createTypes}}: SourceNodesArgs) => {
  createTypes(`
    type kontent_item_rich_text_element_link {
      element: Node! @link(from: "element___NODE")
    }
  `)
}
```
But, when I run a `gatsby develop`, I get this:
```
warn Plugin `gatsby-plugin-ts-config` tried to define the GraphQL type `kontent_item_rich_text_element_link`, which has already been defined by the plugin `@kentico/gatsby-source-kontent`.
```
My theory is that `@kentico/gatsby-source-kontent` defines the type and then `gatsby-plugin-ts-config` tries to redefine the type, so Gatsby throws the warning and doesn't allow the plugin to do so. As a result, my custom typing does not work. This may not even be an issue with this plugin but any direction is helpful! Perhaps there is a way to tell Gatsby to allow this?

I appreciate your time and intention with this plugin! Let me know if there is anything else I can provide to help explain the issue better. 😄

**Comment by Js-Brecht** [comment]
Can you try putting your `createTypes()` call in `createSchemaCustomization`?

**Comment by chriscarrillo** [comment]
Hey @Js-Brecht. Thanks for the prompt reply! I tried to put the call in `createSchemaCustomization` as suggested but I am getting the same error.

**Comment by Js-Brecht** [comment]
This issue is [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/schema.js#L344-L347).  Because your `gatsby-config` is executed a level lower than the default site, the API is being called with `plugin.name = 'gatsby-plugin-ts-config'`.  The schema customization is set up to only allow customizations from the default site or whatever plugin originally created the types.

So we need to pretend that the plugin calling the action is the default site.  Can you try like this?

```js
export const sourceNodes = ({actions: {createTypes}}: SourceNodesArgs) => {
  const types = `
    type kontent_item_rich_text_element_link {
      element: Node! @link(from: "element___NODE")
    }
  `
  createTypes(types, { name: 'default-site-plugin' })
}
```

**Comment by chriscarrillo** [comment]
Ahhh! Perfect! That's what did it. That completely makes sense! Thank you so much!

**Comment by Js-Brecht** [comment]
Awesome, good to know.

I already wrap the default-site node API endpoints, because this plugin does some work in `gatsby-node` itself.  I think I could make this process a little easier by wrapping the actions, too, and "faking" the `default-site-plugin` name.

I'm going to leave this issue open and include this feature in the next version.
