### ISSUE TITLE
gatsby-browser.tsx seems to be ignored during gatsby build

### ISSUE THREAD

**Issue by devuxer** [Js-Brecht/gatsby-plugin-ts-config#28]
Does this plugin support tsx files, specifically gatsby-browser.tsx?

I'm getting an error when I run `gatsby build` (but not `gatsby develop`). Specifically, static HTML rendering is failing because a provider is not getting wrapped. I put a `console.log` statement at the top of my gatsby-browser.tsx file, but the message never appears in the terminal (unlike for gatsby-node.ts or gatsby-config.ts). I also put a `console.log` statement inside a `wrapRootElement` function, but that also doesn't write.

**Comment by Js-Brecht** [comment]
@devuxer it allows you to co-locate your `gatsby-browser`/`gatsby-ssr` next to your `gatsby-config.ts`/`gatsby-node.ts`, but otherwise it lets Gatsby handle them.  You can also leave them in the root of the project next to `gatsby-config.js`, and Gatsby will process them normally.

Can you share some more context about your project, or a minimal reproduction of the issue?

**Comment by devuxer** [comment]
@Js-Brecht , Thanks for your speedy reply.

It appears that when running `gatsby build`, it's considered server-side rendering, so I need to also have a `wrapRootElement` function in gatsby-ssr.tsx as well. When I put a `console.log` in gatsby-ssr.tsx, it *did* appear in the terminal. So, I think that was my problem.
