### ISSUE TITLE
"__esModule" is not allowed

### ISSUE THREAD

**Issue by jonohewitt** [Js-Brecht/gatsby-plugin-ts-config#30]
Hi, I'm trying to use this plugin in a Gatsby v3.0 project and running into this error immediately after `gatsby develop`:

```
error The site's gatsby-config.js failed validation:

"__esModule" is not allowed
not finished open and validate gatsby-configs - 0.542s
```

 Is this an incompatibility with v3 or perhaps something you might have come across before?
 
 ```
// gatsby-config.js

const { generateConfig } = require("gatsby-plugin-ts-config")
module.exports = generateConfig({ configDir: "gatsby-config" })
 ```

All gatsby .ts files in the `gatsby-config` folder

**Comment by Js-Brecht** [comment]
Was it working in v2?

**Comment by jonohewitt** [comment]
I've only tried using it in v3 so far sorry, I can try adding it to an earlier version to find out if that would help?

**Comment by Js-Brecht** [comment]
Eh, it might, but no guarantee.  There's people that are already using this plugin in v3 successfully, so I'm inclined to think it might be something in your project.  What the error tells me is that the `gatsby-*` files are not being transpiled correctly.

Are you able to share your repo or a minimal reproduction?

**Comment by openscript** [comment]
Do you have a clean `.cache` when you try to start?

**Comment by jonohewitt** [comment]
Just worked out the bug was coming from me using ES6 module export syntax in gatsby-config.ts

E.g I was using `export const siteMetadata =`  instead of `module.exports = { siteMetadata: `

Once I switched to the module.exports syntax it worked! Thanks a lot for the help anyway.

**Comment by Js-Brecht** [comment]
You should be able to use es6 without a problem while using this plugin.  This is why I said that your `gatsby-*` files aren’t being transpiled correctly.

In order to figure out why, I would need to know more about your project.  If you can share the repo, or create a minimal reproduction, I could probably tell why this is happening.

**Comment by jonohewitt** [comment]
Ah sorry about that!  [This is the repo](https://github.com/jonohewitt/locavore), the gatsby config files are the `config` folder.

**Comment by Js-Brecht** [comment]
@jonohewitt ah, okay, I see where the problem was.

You were headed in the right direction by changing `/gatsby-config.js` to call `generateConfig()`, and moving the rest of the config into `/config/gatsby-config.ts`.  Inside of `/config/gatsby-config.ts`, you can use es6 without a problem, but the config itself needs to be all one object.

Inside of `/config/gatsby-config.ts`, you can do any one of these formats:
```ts
import { GatsbyConfig } from "gatsby";
const config: GatsbyConfig = {
  ... config settings ...,
};

export default config;

// (can also do)
export default { ... config settings ...} as GatsbyConfig;

// Or, using the more advanced functionality that gatsby-plugin-ts-config provides
import { ITSConfigFn } from "gatsby-plugin-ts-config";

const config: ITSConfigFn<"config"> = (args, props) => {
  return {
    ... config settings ...
  }
}
```

Can see more details on advanced usage in the following:
* [gatsby-api docs](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/docs/GATSBY-API.md)
* [gatsby-config utils](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/docs/GATSBY-CONFIG-UTILS.md)

**Comment by jonohewitt** [comment]
Thanks very much for looking into it and your help! Got it working with ES6 using the first form now 🚀
