### ISSUE TITLE
Unmet Peer dependencies

### ISSUE THREAD

**Issue by iamkimchico** [Js-Brecht/gatsby-plugin-ts-config#44]
Hi

Thank you so much for an awesome plugin and for all the time you invest into this! It's appreciated!

When I use this plugin (v. 2.1.0) I get a huge list of unmet peer dependencies from your plugin.
Now, I'm not a wiz when it comes to npm packages and peer dependencies, so I'm not sure if it's me who are missing something in my package.json or if it's in fact your plugin that needs some updating :) 

It would be awesome not to have all these warnings on each build

<img width="1996" alt="Screenshot 2021-09-08 at 14 54 42" src="https://user-images.githubusercontent.com/59334469/132513501-545ca813-ffcc-4566-b229-b7e7a9157ad8.png">

Thanks again
Have a good day

**Comment by Js-Brecht** [comment]
The warnings are generated because yarn 1 doesn't respect the `peerDependenciesMeta` field in `package.json`.  There's not really a great way to fix this.  I would have to ship both `@babel/core` and `typescript` as production dependencies, which means that version would be used instead of what's in use in your project.  That's not usually a very good idea, because then you could wind up with some weird conflicts between your dev environment and this plugin.

I may ship `@babel/core` itself, since the presets/plugins for it require certain versions, and there's not generally a lot of conflict between your dev environment and babel :thinking:.

A quick fix would be to install `@babel/core` yourself.  It's an easy update though, so can probably do this afternoon.

**Comment by Js-Brecht** [comment]
Can you try `gatsby-plugin-ts-config@2.1.1`?

**Comment by Js-Brecht** [comment]
@iamkimchico have you had a chance to try the updated version?

**Comment by iamkimchico** [comment]
Hi @Js-Brecht 

Sorry for the late reply!

I have testet with the new version and it works! I don't get any warnings on install, develop or build, so I would say you nailed it!

Thanks!
