### ISSUE TITLE
Is the configDir gone in v2?

### ISSUE THREAD

**Issue by iamkimchico** [Js-Brecht/gatsby-plugin-ts-config#45]
Hi

I just updated to v2.1.0 and found that the pluginOptions has changed and more specifically that the configDir is gone? Is this true or am I missing something? If it's gone is there a particular reason? 

I really liked that feature because I could keep all my .ts configs In a separate folder and only have Gatsby-config.js in the root instead of all 4 config files in the root that just points to a .ts version of themselves. 

Thanks again for a great plugin
Have a good day

**Comment by Js-Brecht** [comment]
Yes, unfortunately `configDir` is gone; I really liked that feature too, because it kept the root of my project's much cleaner.

This plugin used to act as a "proxy" between Gatsby and your `.ts` files, which was how I was able to make Gatsby read your project's configurations from a different directory.  The problem with that is it caused a lot of compatibility issues.  See [the v2 rewrite ticket](https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/31#issue-877940417) for details on what kind of problems it caused.

I have a question for you: Is it just the fact that you have to have root files pointing to a `.ts` version of themselves, or is it the fact that you can't store them in a different directory now?

The reason I ask is because I have a CLI in progress that will eliminate the need for any root `.js` files.  It's very close to being finished already; just doing some testing and optimizing.  I will probably be able to release it this weekend.

**Comment by iamkimchico** [comment]
Hi @Js-Brecht 

So sorry for being so late on the reply!

Thanks for the clarification!

I think the problem for me is having "duplicate" files (gatsby-node.js and Gatsby-node.ts). If I could only have .ts I'm fine with having them in root and not In a separate folder. In a perfect world I would love to have both, but the main problem for me is the duplicate files.

Thanks!

**Comment by Js-Brecht** [comment]
@iamkimchico check out [this discussion](https://github.com/Js-Brecht/gatsby-plugin-ts-config/discussions/42#discussioncomment-1529776).  I’ve released `gatsby-ts`, which will let you do that
