### ISSUE TITLE
Gatsby's Webpack caching mechanism cannot resolve `gatsby-node.js`

### ISSUE THREAD

**Issue by kelvindecosta** [Js-Brecht/gatsby-plugin-ts-config#49]
Hello!

I get a few warnings about Webpack Cache when using the following project structure:

```
.
├── gatsby
│   └── config.ts
├── gatsby-browser.ts
├── gatsby-config.js
├── gatsby-nonde.ts
├── gatsby-ssr.ts
```

> I've configured only `gatsby-config.js` to point to `gatsby/config.ts`.

The warning looks like this:

```
Error: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'path/to/project/root/gatsby-node.js'
```

I think the caching mechanism is looking for a specific `gatsby-node.js` file and cannot resolve for `.ts`.

I found this comment (https://github.com/gatsbyjs/gatsby/discussions/28331#discussioncomment-1303233), that seems to address the problem.

My workaround is to configure `gatsby-node.js` to point to a slightly refactored `gatsby/node.ts`.
I hope this helps anyone who might be facing an issue with caching.

Thank you for actively maintaining this project!

**Comment by kelvindecosta** [comment]
This is maybe unrelated to the scope of the project;

I would prefer to use a single `gatsby` directory, with `browser`, `config`, `node`, & `ssr` APIs defined within this directory, either as `.ts` files or directories (`index.ts` with dependencies).

I am using a lot of Gatsby Node APIs and it seems better to use multiple files rather than a single one.

I've noticed some discussion on the use of a CLI to help with the configuration.
I'm just curious about it and whether there are any plans for built-in typescript support (by Gatsby) for `gatsby-config` and `gatsby-node`.

**Comment by Js-Brecht** [comment]
I could've sworn this had been handled already; I remember very clearly somebody opening PR against the core to fix it.

It's not to do with this project; it's actually how Gatsby is resolving `gatsby-node`... they have the extension hard coded.  I can't seem to find the PR _**or**_ the issue anymore, though :thinking:.

---

> I've noticed some discussion on the use of a CLI to help with the configuration.

I do have a CLI for this project about 95% complete... just need a bit more free time to push it over the finish line.  Same goes for first-class Typescript support in the core.  The CLI here will essentially do the same thing that the core will, but with the ability to change/extend the transpiler.

> I would prefer to use a single `gatsby` directory

Do you generally prefer a _separate_ directory for your `gatsby-*` files, or do you mean you would just prefer to keep them all in one place, no matter where that is?  With the CLI, it will be possible to keep all of your `gatsby-*.ts` files in the root of your project.  

I generally prefer to keep my config files in their own directory... it just feels cleaner to me.  However, because Gatsby itself doesn't support a separate directory for `gatsby-*` files, there are numerous compatibility issues with hacking that together, which was how it was done in v1.

**Comment by Js-Brecht** [comment]
Aha, here's the initial report: https://github.com/Js-Brecht/gatsby-plugin-ts-config/pull/32#issuecomment-886926273
And the pull request: https://github.com/gatsbyjs/gatsby/pull/32526

**Comment by kelvindecosta** [comment]
Thank you for your response!

> Do you generally prefer a separate directory for your gatsby-* files, or do you mean you would just prefer to keep them all in one place, no matter where that is? With the CLI, it will be possible to keep all of your gatsby-*.ts files in the root of your project.

To be quite honest, back when I started venturing into web development, I didn't like having many configuration files in my projects. It felt like there were a million things that could go wrong (which is still true).  

Now, I'm much more comfortable with config files.
 As long as they are easily extensible, I don't mind where they're kept.

To answer your question regarding `gatsby-*` files, I don't mind that they're at the root.
I would prefer something like this:

```
.
├── gatsby-node
│   ├── create-pages.ts
│   └── index.ts
├── gatsby-browser.ts
├── gatsby-config.js
├── gatsby-ssr.ts
```

I find that `gatsby-node` can grow very quickly.
I prefer breaking the long functions into their own files.

I suggested a single `gatsby` directory because it feels cleaner to have them all in one place.

Thank you again for taking the time to clear things out!
