### ISSUE TITLE
I have a issue when add babelrc.js to gatsby

### ISSUE THREAD

**Issue by kamontat** [Js-Brecht/gatsby-plugin-ts-config#7]
I add custom babel in Gatsby project but it seems like to resolve completed.

project: https://github.com/kamontat/kamontat/pull/81
ci build error: https://app.circleci.com/pipelines/github/kamontat/kamontat/175/workflows/ef23c3ce-8bfe-41e7-a36d-037daa12d9cb/jobs/439

**Comment by Js-Brecht** [comment]
Hi @kamontat, thanks for opening this issue!

Couple things: 

1. It’s not usually a good idea to mix es6 imports with commonjs exports.

2. This issue shouldn’t be related to this plugin.  This plugin only affects the `gatsby-*` config files, while the issue you’re having is during the bundling of the site, which uses webpack.

3. Instead of using `.babelrc`, can you try using Gatsby’s `onCreateBabelConfig` in `gatsby-node`:

```js
export const onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name: “babel-plugin-macros”
  })
}
```

Let me know if that helps

**Comment by Js-Brecht** [comment]
@kamontat were you able to try my suggestion?

**Comment by kamontat** [comment]
Yes. I tried setBabelPlugin(). And refactoring most of commonjs import/export. I working now. Thanks.

**Comment by Js-Brecht** [comment]
I'm glad to hear that!

I'm going to go ahead and close this issue now.  If you have more problems, please feel free to comment.
